import { Category } from "../types";

export const categories: Category[] = [
    "animals",
    "sports",
    "movies",
    "music",
    "funny",
    "nature",
    "tech",
    "omg",
    "crazy",
    "shrug",
    "smile",
    "awkward",
    "ew",
    "angry",
    "surprised",
    "why",
    "thumbs up",
    "wow",
    "ouch",
    "oops",
    "youre welcome",
    "lazy",
    "stressed",
    "embarrassed",
    "clapping",
    "awesome",
    "jk",
    "nfl",
    "good luck",
    "high five",
    "nervous",
    "duh",
    "aww",
    "scared",
    "bored",
    "sigh",
    "kiss",
    "sad",
    "good night",
    "good morning",
    "confused",
    "chill out",
    "love",
    "happ",
    "cry",
    "yes",
    "no",
    "lol",
    "excited",
    "bye",
    "sorry",
    "congratulations",
    "sleepy",
    "hello",
    "hugs",
    "ok",
    "please",
    "thank",
    "whatever",
    "hungry",
    "dance",
    "annoyed",
  ];